### PR TITLE
fix: eliminate the padding

### LINKED ISSUE #38: The bottom margin is abnormal
Some margin Settings cause some text to be explicitly incomplete.

image

default theme:

image

### PR DESCRIPTION
**Pull request by YangFong**
close #38

### CODE REVIEW

**Comment by YangFong** [comment]
When transparent mode is on, a margin is added, and because of the 'min-width' limit, #38 occurs.

image

**Comment by W1-PopelierE** [comment]
@YangFong 
Could you include a picture of the result?

**Comment by YangFong** [comment]
> @YangFong Could you include a picture of the result?

In the new version of OB, the `margin ` is now `padding`.

It needs to be updated

**Comment by YangFong** [comment]
Before the change:

image

After the changes:

image

**Comment by W1-PopelierE** [comment]
Nice, looking good. Perhaps you could even rebase this to ensure a clean commit history.

**Pull request merged**
